import pyautogui
import time

def main():
    time.sleep(5)
    while True:
        pyautogui.hotkey('esc')
        pyautogui.hotkey('f4')
        time.sleep(6)  # Wait for the game to start
        pyautogui.press('z')
        time.sleep(2)
        pyautogui.moveTo(1576, 561, duration=0.2)
        time.sleep(0.5)
        pyautogui.click(1576, 561)
        time.sleep(0.5)
        pyautogui.click(1576, 561)
        time.sleep(0.2)
        pyautogui.press('.')
        time.sleep(0.2)
        pyautogui.press('.')
        time.sleep(0.2)
        pyautogui.press('/')
        time.sleep(0.2)
        pyautogui.press('/')
        time.sleep(0.2)
        pyautogui.press('/')
        time.sleep(0.2)
        pyautogui.press('/')
        time.sleep(1)
        pyautogui.press('a')
        time.sleep(1)
        pyautogui.moveTo(825, 704, duration=0.2)
        time.sleep(0.5)
        pyautogui.click(825, 704)
        time.sleep(0.5)
        pyautogui.click(825, 704)
        time.sleep(0.5)
        pyautogui.press('/')
        time.sleep(0.2)
        pyautogui.press('/')
        time.sleep(0.2)
        pyautogui.press(',')
        time.sleep(0.2)
        pyautogui.press(',')
        time.sleep(0.2)
        pyautogui.press(',')
        time.sleep(0.2)
        pyautogui.press(',')
        time.sleep(1)
        pyautogui.moveTo(1829, 1011, duration=0.2)
        time.sleep(0.5)
        pyautogui.click(1829, 1011)
        time.sleep(0.5)
        pyautogui.click(1829, 1011)
        time.sleep(5)
        pyautogui.moveTo(837, 234, duration=0.2)
        time.sleep(0.5)
        for _ in range(65):
            pyautogui.click(837, 234)
            time.sleep(5)
        time.sleep(15)
        pyautogui.moveTo(950, 905, duration=0.2)
        time.sleep(1)
        pyautogui.click(950, 905)
        time.sleep(5)
        pyautogui.moveTo(1192, 842, duration=0.2)
        time.sleep(1)
        pyautogui.click(1192, 842)
        time.sleep(3)
        pyautogui.moveTo(1601, 36, duration=0.2)
        time.sleep(0.5)
       //,,,, pyautogui.click(1601, 36)
        time.sleep(1)
        pyautogui.click(1601, 36)
        time.sleep(1)
        pyautogui.moveTo(1075, 831, duration=0.2)
        time.sleep(0.5)
        pyautogui.click(1075, 831)
        time.sleep(1)
        pyautogui.moveTo(1119, 724, duration=0.2)
        time.sleep(0.5)
        pyautogui.click(1119, 724)
        time.sleep(1)

if __name__ == "__main__":
    main()
